In [4]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


### Tensors and operations

In [2]:
tf.constant([[1.,2.,3.],[4.,5.,6.]]) #Matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
tf.constant(42) #Scaler

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [ ]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [6]:
t.shape

TensorShape([2, 3])

In [7]:
t.dtype

tf.float32

### Indexing

In [8]:
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [10]:
t[...,1,tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

### OPS

In [11]:
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [13]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [ ]:
tf.transpose(t) # Take copy

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [17]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

### From/To Numpy

In [ ]:
a=np.array([2.,4.,5.])
tf.constant(a) # to tensor

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [19]:
t.numpy() # to numpy

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

### Ragged Tensors

In [20]:
p = tf.constant(["Café", "Coffee", "caffè", "咖啡"])
r=tf.strings.unicode_decode(p,"UTF8")
r

<tf.RaggedTensor [[67, 97, 102, 233], [67, 111, 102, 102, 101, 101],
 [99, 97, 102, 102, 232], [21654, 21857]]>

In [21]:
print(r[1])

tf.Tensor([ 67 111 102 102 101 101], shape=(6,), dtype=int32)


In [22]:
r.to_tensor()

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[   67,    97,   102,   233,     0,     0],
       [   67,   111,   102,   102,   101,   101],
       [   99,    97,   102,   102,   232,     0],
       [21654, 21857,     0,     0,     0,     0]], dtype=int32)>

### Spare tensors

In [29]:
s=tf.SparseTensor(indices=[[0,1],[1,0],[2,3]],
                  values=[1.,2.,3.],
                  dense_shape=[3,4])

In [31]:
print(s)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [25]:
tf.sparse.to_dense(s)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 3.]], dtype=float32)>

## TensorFlow Functions 

In [1]:
def cube(x):
  return x**3

In [2]:
cube(2)

8

In [5]:
cube(tf.constant(2.0))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

## How TF Functions Trace Python Functions to Extract Their Computation Graphs

In [6]:
@tf.function
def tf_cube(x):
  print("Print:", x)
  return x**3

In [7]:
result=tf_cube(tf.constant(2.0))

Print: Tensor("x:0", shape=(), dtype=float32)


In [8]:
result

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [9]:
result = tf_cube(2)
result = tf_cube(3)
result = tf_cube(tf.constant([[1., 2.]])) # New shape: trace!
result = tf_cube(tf.constant([[3., 4.], [5., 6.]])) # New shape: trace!
result = tf_cube(tf.constant([[7., 8.], [9., 10.], [11., 12.]])) # New shape: trace!

Print: 2
Print: 3
Print: Tensor("x:0", shape=(1, 2), dtype=float32)
Print: Tensor("x:0", shape=(2, 2), dtype=float32)
Print: Tensor("x:0", shape=(3, 2), dtype=float32)


## Handling Variables and Other Resources in TF Functions

In [10]:
counter=tf.Variable(0)

@tf.function
def increment(counter,c=1):
  return counter.assign_add(c)

In [11]:
increment(counter)
increment(counter)

<tf.Tensor: shape=(), dtype=int32, numpy=2>